version: '3.0'
services:
  rasa:
    container_name: rasa_server
    image: rasa/rasa:2.4.0-full
    ports:
      - "5005:5005"
    volumes:
      - ./:/app
    command:
      - run
  app:
    image: kudrkr/repo-covtravbot:14-09-01
    expose: 
      - "5055"
  nginx:
    container_name: nginx
    image: nginx
    depens_on:
      - "rasa"
      - "app"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certs:/etc/letsencrypt/live/safetraveller-bot.com