version: '3.0'
services:
  rasa:
    image: rasa/rasa:2.8.5-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  app:
    image: kudrkr/repo-covtravbot:08-09
    expose: 5055